// pm2 ecosystem config — generated by `surfacemcp init`
// Run: pm2 start ecosystem.config.cjs && pm2 save
module.exports = {
  apps: [
    {
      name: 'surfacemcp-web',
      script: '/root/SurfaceMCP/dist/cli/main.js',
      args: 'serve',
      cwd: '/root/SurfaceMCP/fixtures/vite-app',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        SURFACEMCP_CONFIG: '/root/SurfaceMCP/fixtures/vite-app/surfacemcp.config.json',
      },
      out_file: '/root/SurfaceMCP/fixtures/vite-app/.surfacemcp/logs/out.log',
      error_file: '/root/SurfaceMCP/fixtures/vite-app/.surfacemcp/logs/err.log',
      merge_logs: true,
      autorestart: true,
      watch: false,
    },
  ],
};
