// Build an OpenAPI 3.1 document from a discovered SurfaceMCP catalog, so the
// surface is consumable outside MCP (Swagger UI, Postman import, client codegen)
// and usable as a test oracle. Reuses the extracted input/output schemas.

import type { ToolMeta, JsonSchema2020 } from '../types.js';
import { extractPathParams } from '../server/path-params.js';

const BODY_METHODS = new Set(['POST', 'PUT', 'PATCH']);

export type OpenApiExportOptions = {
  title: string;
  version: string;
  baseUrl?: string;
};

type OpenApiParameter = {
  name: string;
  in: 'path' | 'query';
  required?: boolean;
  schema: JsonSchema2020;
};

function omitKeys(schema: JsonSchema2020, keys: Set<string>): JsonSchema2020 {
  if (!schema.properties) return schema;
  const properties: Record<string, JsonSchema2020> = {};
  for (const [k, v] of Object.entries(schema.properties)) {
    if (!keys.has(k)) properties[k] = v;
  }
  const required = (schema.required ?? []).filter((r) => !keys.has(r));
  return { ...schema, properties, required: required.length ? required : undefined };
}

/** `/users/:id` -> `/users/{id}` (OpenAPI path templating). */
function toOpenApiPath(path: string): string {
  return path.replace(/:([A-Za-z_]\w*)/g, '{$1}');
}

export type OpenApiExportResult = {
  document: Record<string, unknown>;
  /** Count of GraphQL tools skipped (they don't map to REST paths). */
  skippedGraphql: number;
};

export function buildOpenApiDocument(tools: ToolMeta[], opts: OpenApiExportOptions): Record<string, unknown> {
  return buildOpenApiResult(tools, opts).document;
}

/**
 * Like buildOpenApiDocument but also reports how many tools were skipped. GraphQL
 * tools all share `POST <graphqlPath>` with the operation in the body, so they
 * cannot be represented as distinct REST paths — they are omitted rather than
 * collapsed onto one path (which would silently drop all but one operation).
 */
export function buildOpenApiResult(tools: ToolMeta[], opts: OpenApiExportOptions): OpenApiExportResult {
  const paths: Record<string, Record<string, unknown>> = {};
  let skippedGraphql = 0;

  for (const tool of tools) {
    if (tool.graphql) {
      skippedGraphql++;
      continue;
    }
    const openApiPath = toOpenApiPath(tool.path);
    const pathParamNames = new Set(extractPathParams(tool.path).map((p) => p.name));
    const inputProps = tool.inputSchema?.properties ?? {};
    const requiredInput = new Set(tool.inputSchema?.required ?? []);

    const parameters: OpenApiParameter[] = [];
    for (const name of pathParamNames) {
      parameters.push({
        name,
        in: 'path',
        required: true,
        schema: inputProps[name] ?? { type: 'string' },
      });
    }

    const isBody = BODY_METHODS.has(tool.method.toUpperCase());
    if (!isBody) {
      // GET/HEAD/DELETE-like: non-path input goes to the query string.
      for (const [name, schema] of Object.entries(inputProps)) {
        if (pathParamNames.has(name)) continue;
        parameters.push({ name, in: 'query', required: requiredInput.has(name), schema });
      }
    }

    const responseSchema = tool.outputSchema;
    const operation: Record<string, unknown> = {
      operationId: tool.name,
      ...(parameters.length ? { parameters } : {}),
      responses: {
        '200': {
          description: 'Success',
          ...(responseSchema ? { content: { 'application/json': { schema: responseSchema } } } : {}),
        },
      },
      // Provenance so consumers can key back to the stable tool id.
      'x-surfacemcp-tool-id': tool.toolId,
      'x-surfacemcp-side-effect': tool.sideEffectClass,
      'x-surfacemcp-input-confidence': tool.inputSchemaConfidence,
    };

    if (isBody && tool.inputSchema) {
      operation.requestBody = {
        content: { 'application/json': { schema: omitKeys(tool.inputSchema, pathParamNames) } },
      };
    }

    if (!paths[openApiPath]) paths[openApiPath] = {};
    paths[openApiPath]![tool.method.toLowerCase()] = operation;
  }

  const document = {
    openapi: '3.1.0',
    info: {
      title: opts.title,
      version: opts.version,
      description: 'Generated by SurfaceMCP from the discovered API surface.',
    },
    ...(opts.baseUrl ? { servers: [{ url: opts.baseUrl }] } : {}),
    paths,
  };
  return { document, skippedGraphql };
}
